export const WHEEL_SPIN_DURATION = 5.5;
export const SLOT_SPIN_DURATION_MIN = 4;
export const SLOT_SPIN_DURATION_MAX = 5.5;
export const WINNER_DISPLAY_DELAY = 0.5;
export const WHEEL_TOTAL_TIME = WHEEL_SPIN_DURATION + WINNER_DISPLAY_DELAY;
